import React, { createContext, useState, useContext, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: any;
}

const translations = {
  en: {
    auth: {
      loginTitle: 'Welcome Back',
      registerTitle: 'Create Account',
      nameLabel: 'Full Name',
      emailLabel: 'Email Address',
      passwordLabel: 'Password',
      loginBtn: 'Sign In',
      registerBtn: 'Sign Up',
      switchToRegister: "Don't have an account? Sign Up",
      switchToLogin: 'Already have an account? Sign In',
      logout: 'Log Out',
      profile: 'My Profile',
      guest: 'Guest User',
      byAuthor: 'by Mr.HIEN',
    },
    sidebar: {
      dashboard: 'Dashboard',
      viralStrategy: 'Viral Strategy (All-in-One)',
      optimizer: 'Video Optimizer',
      scriptWriter: 'Script Writer',
      trendHunter: 'Trend Hunter',
      thumbnailRater: 'Thumbnail Rater',
      thumbnailMaker: 'Thumbnail Maker',
      videoAudit: 'Video Audit',
      subtitle: 'AI-Powered Organic Growth',
    },
    dashboard: {
      welcome: 'Welcome back,',
      subtitle: 'Your channel growth command center. Select a tool to begin.',
      viralTitle: 'Viral Strategy',
      viralDesc: 'Auto-generate titles, scripts, thumbnails, and growth tactics in one click.',
      viralBtn: 'Create Strategy',
      optimizerTitle: 'Metadata Optimizer',
      optimizerDesc: 'Generate high-CTR titles, engaging descriptions, and perfectly matched tags.',
      optimizerBtn: 'Try Optimizer',
      trendTitle: 'Trend Hunter',
      trendDesc: "Discover what's trending in your niche right now using real-time Google Search data.",
      trendBtn: 'Find Trends',
      scriptTitle: 'Script Writer',
      scriptDesc: 'Turn simple ideas into full, engaging scripts with hooks, content, and CTAs.',
      scriptBtn: 'Write Script',
      auditTitle: 'Video Audit',
      auditDesc: 'Analyze a YouTube link to understand why it is (or isn\'t) getting recommended.',
      auditBtn: 'Audit Video',
      makerTitle: 'Thumbnail Maker',
      makerDesc: 'Generate custom, high-quality thumbnails using advanced AI image generation.',
      makerBtn: 'Create Thumbnail',
      tipsTitle: 'Daily Growth Tips',
      tip1: 'Focus on the first 30 seconds (The Hook).',
      tip2: 'Thumbnails should be readable at small sizes.',
      tip3: 'Reply to comments to boost engagement signals.',
      tip4: 'Use playlists to increase session time.',
      tip5: 'Check your "Audience Retention" graph weekly.',
      tip6: 'Consistency beats intensity.',
    },
    optimizer: {
      title: 'Metadata Optimizer',
      topicLabel: 'Video Topic / Idea',
      topicPlaceholder: 'e.g., How to bake sourdough bread for beginners',
      toneLabel: 'Tone',
      tones: {
        Exciting: 'Exciting',
        Educational: 'Educational',
        Serious: 'Serious',
        Funny: 'Funny',
        Clickbaity: 'Clickbaity'
      },
      btnGenerate: 'Generate Metadata',
      btnGenerating: 'Optimizing...',
      resultTitles: 'Recommended Titles',
      resultDesc: 'Description',
      resultTags: 'Tags',
      error: 'Failed to generate. Please check API Key and try again.',
    },
    script: {
      title: 'Script Writer',
      videoTitleLabel: 'Video Title',
      videoTitlePlaceholder: 'The Main Title of Your Video',
      pointsLabel: 'Key Points (Optional)',
      pointsPlaceholder: 'What should be covered? e.g., Introduction, 3 main tips, Conclusion',
      btnGenerate: 'Generate Script',
      btnGenerating: 'Writing Script...',
      error: 'Error generating script. Please try again.',
    },
    trend: {
      title: 'Trend Hunter',
      nicheLabel: 'Your Niche',
      nichePlaceholder: 'e.g., Tech Reviews, Vegan Cooking, Minecraft',
      btnFind: 'Find Trends',
      analysisTitle: 'Analysis from Web',
      sourcesTitle: 'Sources',
      error: 'Error finding trends. Ensure you have access to Google Search tools.',
    },
    thumbnail: {
      title: 'Thumbnail Rater',
      uploadText: 'Click to upload thumbnail',
      uploadSubtext: 'Supports JPG, PNG',
      contextLabel: 'Video Context (Optional)',
      contextPlaceholder: "e.g. A gaming let's play video about horror games",
      btnAnalyze: 'Analyze Thumbnail',
      btnAnalyzing: 'Analyzing AI Vision...',
      emptyState: 'Upload an image to get AI feedback on color, composition, and CTR potential.',
      loadingState: 'Studying pixels...',
      error: 'Error analyzing image.',
    },
    maker: {
      title: 'Thumbnail Generator',
      promptLabel: 'Image Description',
      promptPlaceholder: 'e.g., A shocked man looking at a flying glowing laptop, vibrant colors, youtube thumbnail style',
      btnGenerate: 'Generate Image',
      btnGenerating: 'Generating...',
      download: 'Download Thumbnail',
      error: 'Failed to generate image. Please try a different prompt.',
    },
    audit: {
      title: 'Video Audit',
      urlLabel: 'YouTube Video URL',
      urlPlaceholder: 'https://www.youtube.com/watch?v=...',
      btnAnalyze: 'Audit Video',
      btnAnalyzing: 'Analyzing Algorithm...',
      scoreTitle: 'Algorithm Score',
      summaryTitle: 'Recommendation Analysis',
      positives: 'Why it works',
      negatives: 'Areas to Improve',
      suggestions: 'Action Plan',
      error: 'Failed to analyze video. Ensure the link is public and valid.',
    },
    viral: {
      title: 'Viral Strategy Generator',
      topicLabel: 'Enter Video Topic OR YouTube URL',
      topicPlaceholder: 'e.g. "iPhone Review" OR "https://youtube.com/watch?v=..."',
      btnGenerate: 'Generate Full Strategy',
      btnGenerating: 'Brainstorming Strategy...',
      trendSection: 'Why this works now',
      titleSection: 'High CTR Titles',
      thumbSection: 'Thumbnail Concept',
      scriptSection: 'Script Outline',
      promoSection: 'Promotion Tactics',
      error: 'Failed to generate strategy.',
      btnDownloadStrategy: 'Download Strategy (.md)',
      downloadThumbnail: 'Download Image',
      analysisSection: 'Competitor Analysis',
      strengths: 'Strengths (Keep)',
      weaknesses: 'Weaknesses (Exploit)',
    }
  },
  vi: {
    auth: {
      loginTitle: 'Chào mừng trở lại',
      registerTitle: 'Tạo tài khoản mới',
      nameLabel: 'Họ và tên',
      emailLabel: 'Địa chỉ Email',
      passwordLabel: 'Mật khẩu',
      loginBtn: 'Đăng Nhập',
      registerBtn: 'Đăng Ký',
      switchToRegister: 'Chưa có tài khoản? Đăng ký ngay',
      switchToLogin: 'Đã có tài khoản? Đăng nhập',
      logout: 'Đăng xuất',
      profile: 'Hồ sơ',
      guest: 'Khách',
      byAuthor: 'by Mr.HIEN',
    },
    sidebar: {
      dashboard: 'Bảng điều khiển',
      viralStrategy: 'Chiến lược Viral (All-in-One)',
      optimizer: 'Tối ưu Video',
      scriptWriter: 'Viết Kịch bản',
      trendHunter: 'Săn Xu hướng',
      thumbnailRater: 'Đánh giá Thumbnail',
      thumbnailMaker: 'Tạo Thumbnail AI',
      videoAudit: 'Phân tích Video',
      subtitle: 'Tăng trưởng tự nhiên với AI',
    },
    dashboard: {
      welcome: 'Chào mừng,',
      subtitle: 'Trung tâm chỉ huy tăng trưởng kênh của bạn. Chọn một công cụ để bắt đầu.',
      viralTitle: 'Chiến lược Viral',
      viralDesc: 'Tự động tạo tiêu đề, kịch bản, ý tưởng thumbnail và chiến thuật tăng trưởng chỉ với 1 cú click.',
      viralBtn: 'Lập Chiến Lược',
      optimizerTitle: 'Tối ưu Metadata',
      optimizerDesc: 'Tạo tiêu đề CTR cao, mô tả hấp dẫn và thẻ (tags) phù hợp nhất.',
      optimizerBtn: 'Thử Tối ưu',
      trendTitle: 'Săn Xu hướng',
      trendDesc: 'Khám phá những gì đang thịnh hành trong ngách của bạn ngay bây giờ bằng dữ liệu Google Tìm kiếm thời gian thực.',
      trendBtn: 'Tìm Xu hướng',
      scriptTitle: 'Viết Kịch bản',
      scriptDesc: 'Biến ý tưởng đơn giản thành kịch bản đầy đủ, hấp dẫn với các đoạn hook, nội dung và lời kêu gọi hành động (CTA).',
      scriptBtn: 'Viết Kịch bản',
      auditTitle: 'Phân tích Video',
      auditDesc: 'Phân tích liên kết YouTube để hiểu lý do tại sao video được (hoặc không được) đề xuất.',
      auditBtn: 'Phân tích ngay',
      makerTitle: 'Tạo Thumbnail AI',
      makerDesc: 'Tạo thumbnail chất lượng cao, tùy chỉnh bằng công nghệ tạo ảnh AI tiên tiến.',
      makerBtn: 'Tạo ngay',
      tipsTitle: 'Mẹo Tăng trưởng Hàng ngày',
      tip1: 'Tập trung vào 30 giây đầu tiên (The Hook).',
      tip2: 'Thumbnail phải dễ đọc ở kích thước nhỏ.',
      tip3: 'Trả lời bình luận để tăng tín hiệu tương tác.',
      tip4: 'Sử dụng danh sách phát để tăng thời gian phiên.',
      tip5: 'Kiểm tra biểu đồ "Giữ chân người xem" hàng tuần.',
      tip6: 'Sự nhất quán quan trọng hơn cường độ.',
    },
    optimizer: {
      title: 'Tối ưu Metadata',
      topicLabel: 'Chủ đề Video / Ý tưởng',
      topicPlaceholder: 'VD: Cách làm bánh mì men chua cho người mới bắt đầu',
      toneLabel: 'Giọng điệu',
      tones: {
        Exciting: 'Hào hứng',
        Educational: 'Giáo dục',
        Serious: 'Nghiêm túc',
        Funny: 'Hài hước',
        Clickbaity: 'Giật gân (Clickbait)'
      },
      btnGenerate: 'Tạo Metadata',
      btnGenerating: 'Đang tối ưu...',
      resultTitles: 'Tiêu đề Đề xuất',
      resultDesc: 'Mô tả',
      resultTags: 'Thẻ (Tags)',
      error: 'Tạo thất bại. Vui lòng kiểm tra API Key và thử lại.',
    },
    script: {
      title: 'Viết Kịch bản',
      videoTitleLabel: 'Tiêu đề Video',
      videoTitlePlaceholder: 'Tiêu đề chính của video',
      pointsLabel: 'Các điểm chính (Tùy chọn)',
      pointsPlaceholder: 'Nội dung cần bao gồm? VD: Giới thiệu, 3 mẹo chính, Kết luận',
      btnGenerate: 'Tạo Kịch bản',
      btnGenerating: 'Đang viết...',
      error: 'Lỗi khi tạo kịch bản. Vui lòng thử lại.',
    },
    trend: {
      title: 'Săn Xu hướng',
      nicheLabel: 'Ngách của bạn',
      nichePlaceholder: 'VD: Review công nghệ, Nấu ăn chay, Minecraft',
      btnFind: 'Tìm Xu hướng',
      analysisTitle: 'Phân tích từ Web',
      sourcesTitle: 'Nguồn',
      error: 'Lỗi khi tìm xu hướng. Đảm bảo bạn có quyền truy cập công cụ Google Search.',
    },
    thumbnail: {
      title: 'Đánh giá Thumbnail',
      uploadText: 'Nhấn để tải lên thumbnail',
      uploadSubtext: 'Hỗ trợ JPG, PNG',
      contextLabel: 'Ngữ cảnh Video (Tùy chọn)',
      contextPlaceholder: 'VD: Video chơi game kinh dị',
      btnAnalyze: 'Đánh giá Thumbnail',
      btnAnalyzing: 'Đang phân tích...',
      emptyState: 'Tải ảnh lên để nhận phản hồi từ AI về màu sắc, bố cục và tiềm năng CTR.',
      loadingState: 'Đang nghiên cứu điểm ảnh...',
      error: 'Lỗi khi phân tích ảnh.',
    },
    maker: {
      title: 'Tạo Thumbnail AI',
      promptLabel: 'Mô tả hình ảnh',
      promptPlaceholder: 'VD: Một người đàn ông sốc khi nhìn vào máy tính, màu sắc rực rỡ, phong cách YouTube',
      btnGenerate: 'Tạo Hình ảnh',
      btnGenerating: 'Đang tạo...',
      download: 'Tải xuống',
      error: 'Tạo ảnh thất bại. Vui lòng thử mô tả khác.',
    },
    audit: {
      title: 'Phân tích Video & Đề xuất',
      urlLabel: 'Liên kết Video YouTube',
      urlPlaceholder: 'https://www.youtube.com/watch?v=...',
      btnAnalyze: 'Phân tích Video',
      btnAnalyzing: 'Đang phân tích thuật toán...',
      scoreTitle: 'Điểm Thuật toán',
      summaryTitle: 'Phân tích Đề xuất',
      positives: 'Điểm mạnh',
      negatives: 'Cần cải thiện',
      suggestions: 'Kế hoạch hành động',
      error: 'Không thể phân tích video. Đảm bảo liên kết là công khai và hợp lệ.',
    },
    viral: {
      title: 'Chiến lược Viral (Tất cả trong 1)',
      topicLabel: 'Nhập Chủ đề hoặc Link YouTube',
      topicPlaceholder: 'VD: "iPhone 16 Review" HOẶC "https://youtube.com/..."',
      btnGenerate: 'Tạo Chiến Lược Toàn Diện',
      btnGenerating: 'Đang lên kế hoạch...',
      trendSection: 'Tại sao chủ đề này hot',
      titleSection: 'Tiêu đề CTR cao',
      thumbSection: 'Ý tưởng Thumbnail',
      scriptSection: 'Dàn ý Kịch bản',
      promoSection: 'Chiến thuật Quảng bá',
      error: 'Không thể tạo chiến lược. Vui lòng thử lại.',
      btnDownloadStrategy: 'Tải xuống Chiến lược (.md)',
      downloadThumbnail: 'Tải ảnh',
      analysisSection: 'Phân tích Đối thủ',
      strengths: 'Điểm Mạnh (Cần học hỏi)',
      weaknesses: 'Điểm Yếu (Cần khai thác)',
    }
  },
  zh: {
    auth: {
      loginTitle: '欢迎回来',
      registerTitle: '创建账户',
      nameLabel: '全名',
      emailLabel: '电子邮件',
      passwordLabel: '密码',
      loginBtn: '登录',
      registerBtn: '注册',
      switchToRegister: '没有账户？立即注册',
      switchToLogin: '已有账户？登录',
      logout: '登出',
      profile: '个人资料',
      guest: '访客',
      byAuthor: 'by Mr.HIEN',
    },
    sidebar: {
      dashboard: '仪表板',
      viralStrategy: '病毒式策略 (一体化)',
      optimizer: '视频优化',
      scriptWriter: '脚本编写',
      trendHunter: '趋势猎人',
      thumbnailRater: '缩略图评分',
      thumbnailMaker: 'AI 缩略图生成',
      videoAudit: '视频诊断',
      subtitle: 'AI驱动的自然增长',
    },
    dashboard: {
      welcome: '欢迎回来，',
      subtitle: '您的频道增长指挥中心。选择一个工具开始。',
      viralTitle: '病毒式策略',
      viralDesc: '一键自动生成标题、脚本、缩略图和增长策略。',
      viralBtn: '创建策略',
      optimizerTitle: '元数据优化器',
      optimizerDesc: '生成高点击率标题、引人入胜的描述和完美匹配的标签。',
      optimizerBtn: '尝试优化',
      trendTitle: '趋势猎人',
      trendDesc: '利用实时谷歌搜索数据发现您所在领域当前的流行趋势。',
      trendBtn: '查找趋势',
      scriptTitle: '脚本编写',
      scriptDesc: '将简单的想法转化为包含钩子、内容和号召性用语（CTA）的完整脚本。',
      scriptBtn: '编写脚本',
      auditTitle: '视频诊断',
      auditDesc: '分析 YouTube 链接，了解为什么它会被（或不会被）推荐。',
      auditBtn: '诊断视频',
      makerTitle: 'AI 缩略图生成',
      makerDesc: '使用先进的 AI 图像生成技术创建自定义的高质量缩略图。',
      makerBtn: '立即创建',
      tipsTitle: '每日增长技巧',
      tip1: '关注前30秒（钩子）。',
      tip2: '缩略图在小尺寸下应清晰可读。',
      tip3: '回复评论以增加互动信号。',
      tip4: '使用播放列表增加会话时间。',
      tip5: '每周检查您的“观众留存率”图表。',
      tip6: '坚持比强度更重要。',
    },
    optimizer: {
      title: '元数据优化器',
      topicLabel: '视频主题 / 想法',
      topicPlaceholder: '例如：初学者的酸种面包烘焙指南',
      toneLabel: '语气',
      tones: {
        Exciting: '激动人心',
        Educational: '教育性',
        Serious: '严肃',
        Funny: '幽默',
        Clickbaity: '标题党 (Clickbaity)'
      },
      btnGenerate: '生成元数据',
      btnGenerating: '优化中...',
      resultTitles: '推荐标题',
      resultDesc: '描述',
      resultTags: '标签',
      error: '生成失败。请检查 API 密钥并重试。',
    },
    script: {
      title: '脚本编写',
      videoTitleLabel: '视频标题',
      videoTitlePlaceholder: '视频的主标题',
      pointsLabel: '关键点（可选）',
      pointsPlaceholder: '应涵盖哪些内容？例如：介绍、3个主要技巧、结论',
      btnGenerate: '生成脚本',
      btnGenerating: '正在编写...',
      error: '生成脚本时出错。请重试。',
    },
    trend: {
      title: '趋势猎人',
      nicheLabel: '您的领域',
      nichePlaceholder: '例如：科技评论、素食烹饪、Minecraft',
      btnFind: '查找趋势',
      analysisTitle: '来自网络的分析',
      sourcesTitle: '来源',
      error: '查找趋势时出错。请确保您有权访问 Google 搜索工具。',
    },
    thumbnail: {
      title: '缩略图评分',
      uploadText: '点击上传缩略图',
      uploadSubtext: '支持 JPG, PNG',
      contextLabel: '视频背景（可选）',
      contextPlaceholder: '例如：关于恐怖游戏的实况视频',
      btnAnalyze: '分析缩略图',
      btnAnalyzing: '正在分析...',
      emptyState: '上传图片以获取 AI 关于颜色、构图和 CTR 潜力的反馈。',
      loadingState: '正在研究像素...',
      error: '分析图片时出错。',
    },
    maker: {
      title: 'AI 缩略图生成',
      promptLabel: '图片描述',
      promptPlaceholder: '例如：一个男人看着发光的笔记本电脑感到震惊，鲜艳的色彩，YouTube 缩略图风格',
      btnGenerate: '生成图片',
      btnGenerating: '生成中...',
      download: '下载图片',
      error: '图片生成失败。请尝试不同的描述。',
    },
    audit: {
      title: '视频诊断与推荐',
      urlLabel: 'YouTube 视频链接',
      urlPlaceholder: 'https://www.youtube.com/watch?v=...',
      btnAnalyze: '诊断视频',
      btnAnalyzing: '正在分析算法...',
      scoreTitle: '算法评分',
      summaryTitle: '推荐分析',
      positives: '优点',
      negatives: '待改进',
      suggestions: '行动计划',
      error: '无法分析视频。请确保链接是公开且有效的。',
    },
    viral: {
      title: '病毒式策略生成器',
      topicLabel: '输入视频主题或 YouTube 链接',
      topicPlaceholder: '例如："iPhone 16 评测" 或 "https://youtube.com/..."',
      btnGenerate: '生成完整策略',
      btnGenerating: '正在规划...',
      trendSection: '为何现在流行',
      titleSection: '高点击率标题',
      thumbSection: '缩略图创意',
      scriptSection: '脚本大纲',
      promoSection: '推广策略',
      error: '策略生成失败。',
      btnDownloadStrategy: '下载策略 (.md)',
      downloadThumbnail: '下载图片',
      analysisSection: '竞争对手分析',
      strengths: '优势 (值得学习)',
      weaknesses: '劣势 (可利用)',
    }
  },
  ja: {
    auth: {
      loginTitle: 'おかえりなさい',
      registerTitle: 'アカウント作成',
      nameLabel: '氏名',
      emailLabel: 'メールアドレス',
      passwordLabel: 'パスワード',
      loginBtn: 'ログイン',
      registerBtn: '登録',
      switchToRegister: 'アカウントをお持ちでないですか？ 登録',
      switchToLogin: 'すでにアカウントをお持ちですか？ ログイン',
      logout: 'ログアウト',
      profile: 'プロフィール',
      guest: 'ゲストユーザー',
      byAuthor: 'by Mr.HIEN',
    },
    sidebar: {
      dashboard: 'ダッシュボード',
      viralStrategy: 'バイラル戦略 (All-in-One)',
      optimizer: '動画最適化',
      scriptWriter: 'スクリプト作成',
      trendHunter: 'トレンドハンター',
      thumbnailRater: 'サムネイル評価',
      thumbnailMaker: 'AIサムネイル作成',
      videoAudit: '動画診断',
      subtitle: 'AIを活用した自然な成長',
    },
    dashboard: {
      welcome: 'ようこそ、',
      subtitle: 'あなたのチャンネル成長の司令塔。ツールを選択して始めましょう。',
      viralTitle: 'バイラル戦略',
      viralDesc: 'タイトル、スクリプト、サムネイル、成長戦術をワンクリックで自動生成します。',
      viralBtn: '戦略を作成',
      optimizerTitle: 'メタデータ最適化',
      optimizerDesc: 'クリック率の高いタイトル、魅力的な説明文、最適なタグを生成します。',
      optimizerBtn: '最適化を試す',
      trendTitle: 'トレンドハンター',
      trendDesc: 'リアルタイムのGoogle検索データを使用して、あなたのニッチで今何が流行っているかを発見します。',
      trendBtn: 'トレンドを探す',
      scriptTitle: 'スクリプト作成',
      scriptDesc: 'シンプルなアイデアを、フック、コンテンツ、CTAを含む完全なスクリプトに変えます。',
      scriptBtn: 'スクリプトを書く',
      auditTitle: '動画診断',
      auditDesc: 'YouTubeリンクを分析し、なぜそれが推奨されている（またはされていない）のかを理解します。',
      auditBtn: '動画を診断',
      makerTitle: 'AIサムネイル作成',
      makerDesc: '高度なAI画像生成技術を使用して、高品質なカスタムサムネイルを作成します。',
      makerBtn: '今すぐ作成',
      tipsTitle: '日々の成長のヒント',
      tip1: '最初の30秒（フック）に集中しましょう。',
      tip2: 'サムネイルは小さいサイズでも読めるように。',
      tip3: 'コメントに返信してエンゲージメントを高めましょう。',
      tip4: '再生リストを使ってセッション時間を延ばしましょう。',
      tip5: '毎週「視聴者維持率」グラフを確認しましょう。',
      tip6: '継続は力なり。',
    },
    optimizer: {
      title: 'メタデータ最適化',
      topicLabel: '動画のトピック / アイデア',
      topicPlaceholder: '例: 初心者向けのサワードウパンの焼き方',
      toneLabel: 'トーン',
      tones: {
        Exciting: 'エキサイティング',
        Educational: '教育的',
        Serious: 'シリアス',
        Funny: '面白い',
        Clickbaity: 'クリックベイト（煽り）'
      },
      btnGenerate: 'メタデータを生成',
      btnGenerating: '最適化中...',
      resultTitles: '推奨タイトル',
      resultDesc: '説明文',
      resultTags: 'タグ',
      error: '生成に失敗しました。APIキーを確認して再試行してください。',
    },
    script: {
      title: 'スクリプト作成',
      videoTitleLabel: '動画タイトル',
      videoTitlePlaceholder: '動画のメインタイトル',
      pointsLabel: 'キーポイント（オプション）',
      pointsPlaceholder: '何を含めるべきですか？ 例: 導入、3つの主なヒント、結論',
      btnGenerate: 'スクリプトを生成',
      btnGenerating: '執筆中...',
      error: 'スクリプトの生成中にエラーが発生しました。再試行してください。',
    },
    trend: {
      title: 'トレンドハンター',
      nicheLabel: 'あなたのニッチ',
      nichePlaceholder: '例: ガジェットレビュー、ヴィーガン料理、マインクラフト',
      btnFind: 'トレンドを探す',
      analysisTitle: 'Webからの分析',
      sourcesTitle: 'ソース',
      error: 'トレンドの検索中にエラーが発生しました。Google検索ツールへのアクセス権があることを確認してください。',
    },
    thumbnail: {
      title: 'サムネイル評価',
      uploadText: 'クリックしてサムネイルをアップロード',
      uploadSubtext: 'JPG, PNG 対応',
      contextLabel: '動画のコンテキスト（オプション）',
      contextPlaceholder: '例: ホラーゲームの実況動画',
      btnAnalyze: 'サムネイルを分析',
      btnAnalyzing: '分析中...',
      emptyState: '画像をアップロードして、色、構図、CTRの可能性に関するAIフィードバックを取得します。',
      loadingState: 'ピクセルを研究中...',
      error: '画像の分析中にエラーが発生しました。',
    },
    maker: {
      title: 'AIサムネイル作成',
      promptLabel: '画像の説明',
      promptPlaceholder: '例: 光るノートパソコンを見てショックを受けている男性、鮮やかな色、YouTubeサムネイルスタイル',
      btnGenerate: '画像を生成',
      btnGenerating: '生成中...',
      download: '画像をダウンロード',
      error: '画像の生成に失敗しました。別の説明を試してください。',
    },
    audit: {
      title: '動画診断と推奨',
      urlLabel: 'YouTube動画リンク',
      urlPlaceholder: 'https://www.youtube.com/watch?v=...',
      btnAnalyze: '動画を診断',
      btnAnalyzing: 'アルゴリズムを分析中...',
      scoreTitle: 'アルゴリズムスコア',
      summaryTitle: '推奨分析',
      positives: '良い点',
      negatives: '改善点',
      suggestions: 'アクションプラン',
      error: '動画を分析できませんでした。リンクが公開されており有効であることを確認してください。',
    },
    viral: {
      title: 'バイラル戦略ジェネレーター',
      topicLabel: '動画のトピックまたはYouTubeリンクを入力',
      topicPlaceholder: '例: "iPhone 16 レビュー" または "https://youtube.com/..."',
      btnGenerate: '完全な戦略を生成',
      btnGenerating: '計画中...',
      trendSection: 'なぜ今流行るのか',
      titleSection: '高CTRタイトル',
      thumbSection: 'サムネイルのアイデア',
      scriptSection: 'スクリプトの概要',
      promoSection: 'プロモーション戦術',
      error: '戦略の生成に失敗しました。',
      btnDownloadStrategy: '戦略をダウンロード (.md)',
      downloadThumbnail: '画像をダウンロード',
      analysisSection: '競合分析',
      strengths: '強み（学ぶべき点）',
      weaknesses: '弱み（攻めるべき点）',
    }
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('vi'); 

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};